# Generated by Django 5.1.15 on 2026-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sona Erme Tarihi"
            ),
        ),
    ]
