# Generated by Django 5.1.15 on 2026-09-10 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wheel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Karar çarkınızın konusu (örn: Akşam Ne Yiyelim?)",
                        max_length=200,
                        verbose_name="Çark Başlığı",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="İsteğe bağlı ek bilgi veya kurallar",
                        verbose_name="Açıklama / Not",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="İşaretlenirse çark herkese açık akışta listelenir ve diğer kullanıcılar da çevirebilir.",
                        verbose_name="Forumda / Herkese Açık Paylaş",
                    ),
                ),
                (
                    "spin_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Çevrilme Sayısı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wheels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Karar Çarkı",
                "verbose_name_plural": "Karar Çarkları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WheelOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=100, verbose_name="Seçenek Metni"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Renk Kodu (Hex veya HSL)",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sıra"),
                ),
                (
                    "wheel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="wheels.wheel",
                        verbose_name="Çark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çark Seçeneği",
                "verbose_name_plural": "Çark Seçenekleri",
                "ordering": ["order", "id"],
            },
        ),
    ]
